# --- Required options --- #

title-head: Catty McCatface's website
subheading: I'm a cat. I'm a kitty cat.

# Name of author
author: Catty McCatface

email: your-email@example.com

baseurl: "Bootstrap-Resume-Jekyll" # the subpath of your site, e.g. blog
url: "http://zemmyang.com" # the base hostname & protocol for your site, e.g. http://example.com

# --- General options --- #

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Excerpt word length - Truncate the excerpt of each post on the blog posts page to the specified number of words
excerpt_length: 50

# The keywords to associate with your website, for SEO purposes
keywords: "jekyll, theme"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "assets/img/profile.jpg"
favicon: "assets/img/favicon.ico"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: false

# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-color: "#EAEAEA"
navbar-text-color: "#404040"
navbar-border-color: "#DDDDDD"
page-color: "#FFFFFF"
text-color: "#404040"
link-color: "#008AFF"
hover-color: "#0085A1"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# --- Web Analytics Section --- #

# Fill in your Google Analytics ID to track your website using Google Analytics
#google_analytics: ""

# --- Comments and Contact --- #

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
#disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# Formspree
#formspree: ""

# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

font-awesome-link: https://use.fontawesome.com/releases/v5.13.0/js/all.js
bootstrap-bundle-min: https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js
jquery-min: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js
jquery-easing-min: https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js
